latitude = float(input('digite a latitude: ').replace(',','.'))
longitude = float(input('digite a longitude: ').replace(',','.'))
tupla = (latitude, longitude)
print(tupla)
lista = list(tupla)
lista.clear()
nlatitude = float(input('digite a nova latitude: ').replace(',','.'))
lista.append(nlatitude)
nlongitude = float(input('digite a nova longitude: ').replace(',','.'))
lista.append(nlongitude)
print(f'As novas cordenadas são {lista}')